<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="buyerfront-moba" ignored="0" name="Test" tests="4" failures="1" timestamp="07 Sep 2020 15:13:49 GMT" time="0.043" errors="0">
  <testcase name="test1" time="0.009" classname="retry_fail_cases.TestNGRetryFailDemo"/>
  <testcase name="test2" time="0.002" classname="retry_fail_cases.TestNGRetryFailDemo"/>
  <testcase name="test3" time="0.004" classname="retry_fail_cases.TestNGRetryFailDemo">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="retry_fail_cases.TestNGRetryFailDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
